"""Bundle ROS2 packages into portable archives for a target distro."""

from __future__ import annotations

import json
import zipfile
from datetime import datetime, timezone
from pathlib import Path
from typing import Any

from lappa import workspace as workspace_store
from lappa.config import WORKSPACES, ensure_dirs
from lappa.ros2_versions import get_selected, get_version


def _bundle_root() -> Path:
    ensure_dirs()
    d = WORKSPACES / "bundles"
    d.mkdir(parents=True, exist_ok=True)
    return d


def list_bundleable() -> list[dict[str, Any]]:
    packs = workspace_store.workspace_packages()
    return [
        {
            "name": p.name,
            "path": str(p.path),
            "description": p.description,
            "files": len(p.files),
        }
        for p in packs
    ]


def _iter_files(root: Path):
    for p in sorted(root.rglob("*")):
        if not p.is_file():
            continue
        rel = p.relative_to(root).as_posix()
        if any(part.startswith(".") for part in rel.split("/")):
            continue
        if "__pycache__" in rel or rel.endswith(".pyc"):
            continue
        yield p, rel


def package_bundle(
    package_names: list[str] | None = None,
    distro: str | None = None,
    out_name: str | None = None,
) -> dict[str, Any]:
    """Create a zip containing one or more ROS2 packages + Lappa manifest."""
    selected = get_version(distro) if distro else get_selected()
    if not selected:
        selected = get_selected()
    distro_id = selected["id"]

    available = {p.name: p for p in workspace_store.workspace_packages()}
    requested = package_names or list(available.keys())
    selected_packages = []
    missing = []
    for name in requested:
        try:
            selected_packages.append(workspace_store.resolve_package_ref(name, base_dir=Path.cwd()))
        except FileNotFoundError:
            pkg = available.get(name)
            if pkg:
                selected_packages.append(pkg)
            else:
                missing.append(name)
    if missing:
        raise ValueError(f"unknown packages: {missing}")
    names = [pkg.name for pkg in selected_packages]

    stamp = datetime.now(timezone.utc).strftime("%Y%m%d_%H%M%S")
    base = out_name or f"lappa_{distro_id}_{'_'.join(names[:3])}{'_etc' if len(names) > 3 else ''}_{stamp}"
    base = base.replace(" ", "_")
    zip_path = _bundle_root() / f"{base}.zip"

    manifest = {
        "format": "lappa-ros2-bundle/v1",
        "created_at": datetime.now(timezone.utc).isoformat(),
        "ros2_distro": distro_id,
        "ros2_meta": selected,
        "packages": [],
        "install_hint": [
            f"mkdir -p ~/lappa_ws/src && unzip {zip_path.name} -d ~/lappa_ws/src",
            f"source /opt/ros/{distro_id}/setup.bash",
            "cd ~/lappa_ws && colcon build --symlink-install",
            "source install/setup.bash",
        ],
    }

    with zipfile.ZipFile(zip_path, "w", compression=zipfile.ZIP_DEFLATED) as zf:
        for pkg in selected_packages:
            name = pkg.name
            prefix = f"src/{name}"
            file_count = 0
            for path, rel in _iter_files(pkg.path):
                zf.write(path, f"{prefix}/{rel}")
                file_count += 1
            # per-package distro stamp
            stamp_body = json.dumps(
                {
                    "package": name,
                    "target_ros2": distro_id,
                    "bundled_by": "lappa",
                },
                indent=2,
            )
            zf.writestr(f"{prefix}/lappa_target.json", stamp_body)
            manifest["packages"].append(
                {
                    "name": name,
                    "files": file_count + 1,
                    "description": pkg.description,
                }
            )
        zf.writestr("lappa_manifest.json", json.dumps(manifest, indent=2))
        zf.writestr(
            "README_BUNDLE.md",
            f"""# Lappa ROS2 bundle ({distro_id})

Packages: {', '.join(names)}

## Install on Linux with ROS2 {distro_id}

```bash
source /opt/ros/{distro_id}/setup.bash
mkdir -p ~/lappa_ws/src
unzip {zip_path.name} -d /tmp/lappa_bundle
cp -r /tmp/lappa_bundle/src/* ~/lappa_ws/src/
cd ~/lappa_ws && colcon build --symlink-install
source install/setup.bash
```

Generated by Lappa packager.
""",
        )

    return {
        "ok": True,
        "path": str(zip_path),
        "filename": zip_path.name,
        "size_bytes": zip_path.stat().st_size,
        "ros2_distro": distro_id,
        "packages": names,
        "manifest": manifest,
    }


def list_bundles() -> list[dict[str, Any]]:
    root = _bundle_root()
    out = []
    for p in sorted(root.glob("*.zip"), reverse=True):
        out.append(
            {
                "filename": p.name,
                "path": str(p),
                "size_bytes": p.stat().st_size,
                "mtime": p.stat().st_mtime,
            }
        )
    return out


def resolve_package_path(name_or_path: str) -> Path:
    return workspace_store.resolve_package_ref(name_or_path, base_dir=Path.cwd()).path
