"""ROS2 distro catalog for Docker images + package metadata."""

from __future__ import annotations

import json
from pathlib import Path
from typing import Any

from lappa.config import WORKSPACES, ensure_dirs

# Supported Lappa targets (Ubuntu base for official ros: tags)
ROS2_DISTROS: dict[str, dict[str, Any]] = {
    "humble": {
        "name": "Humble Hawksbill",
        "codename": "humble",
        "ubuntu": "22.04",
        "status": "LTS",
        "docker_image": "ros:humble-ros-base",
        "eol": "2027-05",
        "python": "3.10",
        "default": True,
        "notes": "Recommended for Windows Docker + long support",
    },
    "iron": {
        "name": "Iron Irwini",
        "codename": "iron",
        "ubuntu": "22.04",
        "status": "EOL",
        "docker_image": "ros:iron-ros-base",
        "eol": "2024-11",
        "python": "3.10",
        "default": False,
        "notes": "Still useful for iron-tagged stacks",
    },
    "jazzy": {
        "name": "Jazzy Jalisco",
        "codename": "jazzy",
        "ubuntu": "24.04",
        "status": "LTS",
        "docker_image": "ros:jazzy-ros-base",
        "eol": "2029-05",
        "python": "3.12",
        "default": False,
        "notes": "Current LTS on Ubuntu 24.04",
    },
    "kilted": {
        "name": "Kilted Kaiju",
        "codename": "kilted",
        "ubuntu": "24.04",
        "status": "rolling-track",
        "docker_image": "ros:kilted-ros-base",
        "eol": "2026-11",
        "python": "3.12",
        "default": False,
        "notes": "Interim release after Jazzy",
    },
    "rolling": {
        "name": "Rolling Ridley",
        "codename": "rolling",
        "ubuntu": "latest",
        "status": "rolling",
        "docker_image": "ros:rolling-ros-base",
        "eol": "n/a",
        "python": "3.12+",
        "default": False,
        "notes": "Bleeding edge — for CI experimentation",
    },
}

_STATE_FILE = "ros2_version.json"


def list_versions() -> list[dict[str, Any]]:
    out = []
    for key, meta in ROS2_DISTROS.items():
        row = {"id": key, **meta}
        out.append(row)
    return out


def get_version(distro: str) -> dict[str, Any] | None:
    key = (distro or "").strip().lower()
    if key not in ROS2_DISTROS:
        return None
    return {"id": key, **ROS2_DISTROS[key]}


def default_version() -> str:
    for k, v in ROS2_DISTROS.items():
        if v.get("default"):
            return k
    return "humble"


def _state_path() -> Path:
    ensure_dirs()
    return WORKSPACES / _STATE_FILE


def get_selected() -> dict[str, Any]:
    path = _state_path()
    if path.is_file():
        try:
            data = json.loads(path.read_text(encoding="utf-8"))
            vid = data.get("id") or data.get("version")
            meta = get_version(str(vid))
            if meta:
                return {**meta, "selected": True}
        except (json.JSONDecodeError, OSError):
            pass
    d = default_version()
    return {**get_version(d), "selected": True}  # type: ignore[misc]


def set_selected(distro: str) -> dict[str, Any]:
    meta = get_version(distro)
    if not meta:
        raise ValueError(f"unknown ROS2 distro: {distro}. Choose from {list(ROS2_DISTROS)}")
    ensure_dirs()
    _state_path().write_text(json.dumps({"id": meta["id"]}, indent=2), encoding="utf-8")
    return {**meta, "selected": True}


def dockerfile_for(distro: str) -> str:
    """Dockerfile that loads a full ROS2 base + colcon so packages build & launch."""
    meta = get_version(distro) or get_version(default_version())
    assert meta
    image = meta["docker_image"]
    code = meta["codename"]
    # Install ament tooling + messages so `colcon build` and `ros2 launch <pkg>` work.
    return f"""# Generated by Lappa — ROS2 {meta['name']}
# Loads ROS2 distro, colcon, and launch stack for real package builds.
FROM {image}

ENV DEBIAN_FRONTEND=noninteractive
ENV ROS_DISTRO={code}
ENV LANG=C.UTF-8

RUN apt-get update && apt-get install -y --no-install-recommends \\
    python3-pip \\
    python3-colcon-common-extensions \\
    python3-rosdep \\
    build-essential \\
    ros-{code}-rclpy \\
    ros-{code}-launch \\
    ros-{code}-launch-ros \\
    ros-{code}-std-msgs \\
    ros-{code}-geometry-msgs \\
    ros-{code}-sensor-msgs \\
    ros-{code}-nav-msgs \\
    ros-{code}-ros2cli \\
    ros-{code}-ros2launch \\
    ros-{code}-ros2pkg \\
    ros-{code}-ros2run \\
    ros-{code}-ros2node \\
    ros-{code}-ros2topic \\
    || true \\
    && rm -rf /var/lib/apt/lists/*

WORKDIR /ws
# Demo packages bind-mount here: /ws/src/<pkg>
RUN mkdir -p /ws/src /ws/log /ws/build /ws/install
COPY entrypoint.sh /entrypoint.sh
COPY ros2_ws.sh /ros2_ws.sh
RUN chmod +x /entrypoint.sh /ros2_ws.sh

ENTRYPOINT ["/entrypoint.sh"]
# Keep ROS sourced; sleep so IDE can docker-exec colcon + ros2 launch
CMD ["bash", "-lc", "source /opt/ros/{code}/setup.bash && echo \\"[lappa] ROS2 {code} loaded · workspace /ws · demos at /ws/src\\" && sleep infinity"]
"""
